# -*- coding: utf-8 -*-
"""Video_2_03_alfa zvuk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-zy2f5PpXsJSCD7dkmOiAPCxS2n5Wh7V

# 🎬 Video Generator v 2.03 se komentářem
Automatizovaný generátor realitních videí s Ken Burns efektům, supersamplingem a automatickou detekcí prostředí (Colab/GitHub Actions).
"""

# Instalace a importy
import subprocess, sys
def install(package): subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", package])

try: import requests
except ImportError: install('requests')

import json, os, shutil, random, zipfile, time, re, io, collections, glob
import numpy as np
import cv2
from PIL import Image, ImageDraw, ImageFont
from moviepy.editor import ImageClip, VideoFileClip, concatenate_videoclips, AudioFileClip, afx
from proglog import ProgressBarLogger

try:
    from google.colab import files, userdata
    IS_COLAB = True
except ImportError:
    IS_COLAB = False

# Definovani zakladnich cest
INPUT_DIR = "vstupni_media_zgk"
ENHANCED_DIR = "vylepsene_fotografie_zgk"
LOGO_CONFIG_PATH = "logo_config.txt"
MUSIC_FILE = "background_music.mp3"
TARGET_FPS = 30

JOB_CONFIG = None
JOB_CONFIG_PATH = None
if not IS_COLAB:
    if len(sys.argv) < 2:
        raise SystemExit("Headless běh vyžaduje cestu k job.json: python video.py job.json")
    JOB_CONFIG_PATH = sys.argv[1]
    with open(JOB_CONFIG_PATH, "r", encoding="utf-8") as _f:
        JOB_CONFIG = json.load(_f)

def notify_video_ready(video_path):
    """
    Zavolá notify.py, aby o hotovém videu poslal makléři e-mail s odkazem
    na Disk. Volá se dvakrát za běh (video 1 = output.mp4, video 2 =
    video_final.mp4), pokaždé zvlášť - notify.py pošle jeden e-mail
    s jedním videem, takže tělo POST požadavku na Apps Script zůstává
    malé (jedno video na callback, ne obě najednou).
    V Colabu se přeskakuje - tam notify.py ani job.json nejsou k dispozici.
    """
    if IS_COLAB or not JOB_CONFIG_PATH:
        print(f"\n🔔 (Colab) Video {video_path} je hotové – notify.py se v Colabu nevolá.")
        return

    result_path = f"render_result_{os.path.basename(video_path)}.json"
    try:
        with open(result_path, "w", encoding="utf-8") as f:
            json.dump({"video_file": video_path}, f)

        subprocess.run(
            [sys.executable, "notify.py",
             "--status", "success",
             "--job", JOB_CONFIG_PATH,
             "--result", result_path],
            check=True,
        )
        print(f"\n🔔 notify.py odesláno pro {video_path}")
    except Exception as e:
        print(f"\n❌ Chyba při volání notify.py pro {video_path}: {e}")

# @title ⚙️ HLAVNÍ KONFIGURACE (Nastavení videa)

# --- Verze a AI nastavení ---
VERSION = "2.03" # @param {type:"string"}
GEMINI_MODEL = "gemini-3.1-flash-lite" # @param {type:"string"}

# --- Nastavení Hlasu a Titulků ---
VOICE_SPEED = "-10%" # @param ["-20%", "-15%", "-10%", "-5%", "+0%", "+5%", "+10%", "+15%", "+20%", "+25%", "+30%"]
VOICE_START_DELAY = 5.0 # @param {type:"number"}
VOICE_END_PADDING = 5.0 # @param {type:"number"}
SUBTITLE_SIZE = 26 # @param {type:"number"}
SUBTITLE_COLOR = "white" # @param {type:"string"}
SUBTITLE_Y_POSITION = 0.80 # @param {type:"number"}

# --- Texty a Barvy ---
TEXT_TOP = "Prodej RD 5+kk 160 m², pozemek 359 m²"  # @param {type:"string"}
FONT_SIZE_TOP = 24  # @param {type:"number"}
TEXT_BOTTOM = "Popovice - okr. Benešov"  # @param {type:"string"}
FONT_SIZE_BOTTOM = 20  # @param {type:"number"}
TEXT_COLOR = "white"  # @param {type:"string"}
LINE_COLOR = "white"  # @param {type:"string"}
LINE_VARIANT = "LINE 2"  # @param ["LINE 1", "LINE 2"]
LINE_SPACING = 7  # @param {type:"number"}

# --- Makléř & RK ---
MAKLER_JMENO = "FRANTIŠEK PROCHÁZKA"  # @param {type:"string"}
MAKLER_BOLD = True  # @param {type:"boolean"}
MAKLER_ITALIC = False  # @param {type:"boolean"}
RK_NAZEV = "HVB Real Estate "  # @param {type:"string"}
RK_BOLD = True  # @param {type:"boolean"}
RK_ITALIC = False  # @param {type:"boolean"}
MAKLER_EMAIL = "fprochazka@hvbreal.cz"  # @param {type:"string"}
MAKLER_TELEFON = "+420 123 456 789"  # @param {type:"string"}
FONT_SIZE_MAKLER = 26  # @param {type:"number"}

# --- Technické nastavení obrazu ---
MIN_IMAGE_DURATION = 3  # @param {type:"number"}
MAX_IMAGE_DURATION = 5  # @param {type:"number"}
MOTION_MODE = "random"  # @param ["random", "zoom_in", "zoom_out", "pan_left_to_right", "pan_right_to_left", "pan_top_to_bottom", "pan_bottom_to_top", "zoom_in_left", "zoom_in_right", "zoom_out_left", "zoom_out_right"]
VIDEO_FADE_IN = 6  # @param {type:"number"}
VIDEO_FADE_OUT = 6  # @param {type:"number"}

# --- Kvalita a Pohyb ---
MOTION_OVERSCAN = 1.28  # @param {type:"number"}
SUPERSAMPLE = 2  # @param {type:"number"}
ZOOM_SPEED = 0.05
PAN_ZOOM_FACTOR = 1.05
PAN_STEP_PERCENT = 60

# --- Hudba ---
VOLUME = 50  # @param {type:"slider", min:0, max:100, step:1}
AUDIO_FADE_IN = 8  # @param {type:"number"}
AUDIO_FADE_OUT = 8  # @param {type:"number"}
NAHRAT_NOVE_SOUBORY = False  # @param {type:"boolean"}

if not IS_COLAB and JOB_CONFIG:
    _cfg = JOB_CONFIG.get("config", {})
    TEXT_TOP = _cfg.get("TEXT_TOP", TEXT_TOP)
    TEXT_BOTTOM = _cfg.get("TEXT_BOTTOM", TEXT_BOTTOM)
    MAKLER_JMENO = _cfg.get("MAKLER_JMENO", MAKLER_JMENO)
    MAKLER_EMAIL = _cfg.get("MAKLER_EMAIL", MAKLER_EMAIL)
    MAKLER_TELEFON = _cfg.get("MAKLER_TELEFON", MAKLER_TELEFON)
    RK_NAZEV = _cfg.get("RK_NAZEV", RK_NAZEV)

GLOBAL_TEXT = f"{TEXT_TOP};{TEXT_BOTTOM}"
OUTPUT_FILE = "output.mp4"

# Příprava složek a nahrání/stažení fotografií
for folder in [INPUT_DIR, ENHANCED_DIR]:
    if os.path.exists(folder):
        shutil.rmtree(folder)
    os.makedirs(folder)

if IS_COLAB:
    if 'music_history' not in globals(): globals()['music_history'] = []
    if os.path.exists(LOGO_CONFIG_PATH):
        with open(LOGO_CONFIG_PATH, 'r') as f:
            saved_logo = f.read().strip()
            if os.path.exists(saved_logo):
                globals()['LOGO_FILE'] = saved_logo
    if 'LOGO_FILE' not in globals(): globals()['LOGO_FILE'] = None

    VYBRANA_HUDBA = "hudba 1 (1).mp3"
    NAHRAT_NOVE_SOUBORY = True

    if NAHRAT_NOVE_SOUBORY or (not globals()['LOGO_FILE'] and not globals()['music_history']):
        print("📂 Režim nahrávání aktivován. Vyberte soubory...")
        uploaded_assets = files.upload()
        for name, data in uploaded_assets.items():
            ext = name.lower().split('.')[-1]
            if ext in ['png', 'jpg', 'jpeg', 'webp', 'bmp']:
                path = os.path.join(INPUT_DIR, name)
                with open(path, 'wb') as f:
                    f.write(data)
                globals()['LOGO_FILE'] = path
                with open(LOGO_CONFIG_PATH, 'w') as f:
                    f.write(path)
                print(f"✅ Soubor uložen: {name}")
            elif ext in ['mp3', 'wav']:
                with open(name, 'wb') as f:
                    f.write(data)
                if name not in globals()['music_history']:
                    globals()['music_history'].append(name)

    active_music = VYBRANA_HUDBA if VYBRANA_HUDBA in globals()['music_history'] else (globals()['music_history'][-1] if globals()['music_history'] else None)
    if active_music and os.path.exists(active_music):
        shutil.copy(active_music, MUSIC_FILE)
        print(f"🎵 Aktivní hudba: {active_music}")
else:
    if JOB_CONFIG and "image_urls" in JOB_CONFIG:
        image_urls = JOB_CONFIG["image_urls"]
        print(f"📥 Stahuji {len(image_urls)} fotek...")
        for i, url in enumerate(image_urls):
            try:
                r = requests.get(url, timeout=60)
                r.raise_for_status()
                ext = "jpg"
                ctype = r.headers.get("Content-Type", "")
                if "png" in ctype: ext = "png"
                elif "webp" in ctype: ext = "webp"
                with open(os.path.join(INPUT_DIR, f"foto_{i+1:03d}.{ext}"), "wb") as f:
                    f.write(r.content)
            except Exception as e:
                print(f"❌ Chyba při stahování {url}: {e}")
        print(f"✅ Staženo {len(os.listdir(INPUT_DIR))} fotek.")

    hudba_dir = "hudba"
    if os.path.exists(hudba_dir):
        available_music = [os.path.join(hudba_dir, f) for f in os.listdir(hudba_dir) if f.lower().endswith('.mp3')]
        if available_music:
            _music_src = random.choice(available_music)
            shutil.copy(_music_src, MUSIC_FILE)
            print(f"🎵 Vybraná hudba: {_music_src}")

import re

def natural_sort_key(s):
    return [int(text) if text.isdigit() else text.lower() for text in re.split('([0-9]+)', s)]

image_files = []

def get_auto_aspect_ratio():
    if not image_files:
        return "16:9"
    try:
        with Image.open(image_files[0]) as first_img:
            w, h = first_img.size
            ratio = w / h
            return "16:9" if abs(ratio - (16/9)) < abs(ratio - (4/3)) else "4:3"
    except:
        return "16:9"

DETECTED_RATIO = "16:9"
TARGET_W, TARGET_H = (1920, 1080)
WORK_W, WORK_H = 1920, 1080

ALL_MOTION_MODES = [
    "zoom_in", "zoom_out", "pan_left_to_right", "pan_right_to_left",
    "pan_top_to_bottom", "pan_bottom_to_top", "zoom_in_left", "zoom_in_right",
    "zoom_out_left", "zoom_out_right"
]

def get_font(is_bold=False, is_italic=False, size=24):
    font_paths = []
    if is_bold and is_italic:
        font_paths = ["/usr/share/fonts/truetype/montserrat/Montserrat-BoldItalic.ttf", "/usr/share/fonts/truetype/dejavu/DejaVuSans-BoldOblique.ttf"]
    elif is_bold:
        font_paths = ["/usr/share/fonts/truetype/montserrat/Montserrat-Bold.ttf", "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"]
    elif is_italic:
        font_paths = ["/usr/share/fonts/truetype/montserrat/Montserrat-Italic.ttf", "/usr/share/fonts/truetype/dejavu/DejaVuSans-Oblique.ttf"]
    else:
        font_paths = ["/usr/share/fonts/truetype/montserrat/Montserrat-Regular.ttf", "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"]

    for path in font_paths:
        if os.path.exists(path):
            try: return ImageFont.truetype(path, int(size))
            except: pass
    return ImageFont.load_default()

def create_centered_info_card(lines, duration, is_intro=True):
    img = Image.new("RGB", (TARGET_W, TARGET_H), color="black")
    draw = ImageDraw.Draw(img)
    logo_path = next((f for f in ["HVBlogo.png", "HVBlogo (1).png"] if os.path.exists(f)), None)

    header_content = [(lines[0], get_font(MAKLER_BOLD, MAKLER_ITALIC, FONT_SIZE_MAKLER)), ("&", get_font(True, False, FONT_SIZE_MAKLER)), (lines[1], get_font(RK_BOLD, RK_ITALIC, FONT_SIZE_MAKLER))]
    footer_content = [(l, get_font(False, "@" in l, FONT_SIZE_MAKLER * 0.8)) for l in lines[2:]] if not is_intro else []

    line_h = draw.textbbox((0, 0), "Ay", font=header_content[2][1])[3] + 25
    total_h = (len(header_content) * line_h) + 80 + (len(footer_content) * line_h * 0.8) + (150 if logo_path else 0)
    curr_y = (TARGET_H - total_h) // 2

    for text, font in header_content:
        w = draw.textbbox((0, 0), text, font=font)[2]
        draw.text(((TARGET_W - w) // 2, curr_y), text, font=font, fill=TEXT_COLOR)
        curr_y += line_h

    rk_w = draw.textbbox((0, 0), lines[1], font=header_content[2][1])[2]
    draw.line([(TARGET_W - rk_w*1.2)//2, curr_y+40, (TARGET_W + rk_w*1.2)//2, curr_y+40], fill="white", width=3)
    curr_y += 80

    for text, font in footer_content:
        w = draw.textbbox((0, 0), text, font=font)[2]
        draw.text(((TARGET_W - w) // 2, curr_y), text, font=font, fill=TEXT_COLOR)
        curr_y += line_h * 0.8

    if logo_path:
        logo = Image.open(logo_path).convert("RGBA")
        logo.thumbnail((400, 110), Image.Resampling.LANCZOS)
        img.paste(logo, ((TARGET_W - logo.width)//2, int(curr_y + 20)), logo)

    return ImageClip(np.array(img)).set_duration(duration)

def draw_text_overlay(image_np, text_str):
    img = Image.fromarray(image_np).convert("RGBA")
    draw = ImageDraw.Draw(img)
    margin = 60
    font_top, font_bottom = get_font(True, False, FONT_SIZE_TOP), get_font(False, False, FONT_SIZE_BOTTOM)

    parts = text_str.split(";")
    top_text, bottom_text = parts[0].strip(), parts[1].strip() if len(parts) > 1 else ""

    w_top, h_top = draw.textbbox((0, 0), top_text, font=font_top)[2], draw.textbbox((0, 0), top_text, font=font_top)[3]
    w_bottom, h_bottom = draw.textbbox((0, 0), bottom_text, font=font_bottom)[2], draw.textbbox((0, 0), bottom_text, font=font_bottom)[3]

    line_y_mid = TARGET_H - margin - 20 - h_bottom - LINE_SPACING
    draw.text((margin, TARGET_H - margin - 20 - h_bottom), bottom_text, font=font_bottom, fill=TEXT_COLOR)
    draw.text((margin, line_y_mid - h_top - LINE_SPACING), top_text, font=font_top, fill=TEXT_COLOR)

    if LINE_VARIANT == "LINE 2":
        draw.line([(margin-20, line_y_mid - h_top - 20), (margin-20, TARGET_H - margin - 10)], fill=LINE_COLOR, width=4)
        draw.line([(margin-20, line_y_mid - h_top - 20), (margin-20 + max(w_top, w_bottom)*0.3, line_y_mid - h_top - 20)], fill=LINE_COLOR, width=4)
        draw.line([(margin-20, TARGET_H - margin - 10), (margin + max(w_top, w_bottom), TARGET_H - margin - 10)], fill=LINE_COLOR, width=4)

    logo_path = "logo.png" if os.path.exists("logo.png") else None
    if logo_path:
        logo = Image.open(logo_path).convert("RGBA")
        # Dynamická výška loga podle textového bloku
        target_h = h_top + h_bottom + 40
        logo.thumbnail((500, target_h), Image.Resampling.LANCZOS)

        logo_x = TARGET_W - margin - logo.width
        logo_y = line_y_mid - h_top - 10
        text_right_edge = margin + max(w_top, w_bottom) + 20

        # Oprava bod 3: Pokud se logo nevejde (kolize s textem), nevykresluj ho
        if logo_x >= text_right_edge:
            img.paste(logo, (logo_x, logo_y), logo)

    return np.array(img.convert("RGB"))

_LAST_MOTION_MODE = None
def _ease_in_out(t):
    t = max(0.0, min(1.0, t))
    return t * t * (3.0 - 2.0 * t)

def _crop_for_mode(mode, e, img_w, img_h):
    zoom_lo, zoom_hi = 1.0, 1.0 + ZOOM_SPEED
    def centered(zoom):
        sw, sh = TARGET_W / zoom, TARGET_H / zoom
        return sw, sh, (img_w - sw) / 2.0, (img_h - sh) / 2.0
    def drifting(zoom, direction):
        sw, sh = TARGET_W / zoom, TARGET_H / zoom
        max_shift = max(0.0, (img_w - sw) / 2.0)
        cx = (img_w - sw) / 2.0 + direction * max_shift * e
        cx = max(0.0, min(img_w - sw, cx))
        return sw, sh, cx, (img_h - sh) / 2.0
    def panning(axis, reverse):
        zoom = max(1.0, PAN_ZOOM_FACTOR)
        sw, sh = TARGET_W / zoom, TARGET_H / zoom
        if axis == "x":
            throw = max(0.0, img_w - sw) * (PAN_STEP_PERCENT / 100.0)
            c = (img_w - sw) / 2.0
            start, end = c - throw / 2.0, c + throw / 2.0
            if reverse: start, end = end, start
            cx = max(0.0, min(img_w - sw, start + e * (end - start)))
            return sw, sh, cx, (img_h - sh) / 2.0
        else:
            throw = max(0.0, img_h - sh) * (PAN_STEP_PERCENT / 100.0)
            c = (img_h - sh) / 2.0
            start, end = c - throw / 2.0, c + throw / 2.0
            if reverse: start, end = end, start
            cy = max(0.0, min(img_h - sh, start + e * (end - start)))
            return sw, sh, (img_w - sw) / 2.0, cy

    if mode == "zoom_in": return centered(zoom_lo + (zoom_hi - zoom_lo) * e)
    if mode == "zoom_out": return centered(zoom_hi - (zoom_hi - zoom_lo) * e)
    if mode == "pan_left_to_right": return panning("x", reverse=False)
    if mode == "pan_right_to_left": return panning("x", reverse=True)
    if mode == "pan_top_to_bottom": return panning("y", reverse=False)
    if mode == "pan_bottom_to_top": return panning("y", reverse=True)
    if mode == "zoom_in_left": return drifting(zoom_lo + (zoom_hi - zoom_lo) * e, -1)
    if mode == "zoom_in_right": return drifting(zoom_lo + (zoom_hi - zoom_lo) * e, +1)
    if mode == "zoom_out_left": return drifting(zoom_hi - (zoom_hi - zoom_lo) * e, -1)
    if mode == "zoom_out_right": return drifting(zoom_hi - (zoom_hi - zoom_lo) * e, +1)
    return centered(zoom_lo)

def _pick_motion_mode():
    global _LAST_MOTION_MODE
    if MOTION_MODE != "random": return MOTION_MODE
    choices = ALL_MOTION_MODES
    mode = random.choice(choices)
    tries = 0
    while mode == _LAST_MOTION_MODE and tries < 10:
        mode = random.choice(choices)
        tries += 1
    _LAST_MOTION_MODE = mode
    return mode

def apply_smooth_smart_motion(img_path, duration, text_overlay=""):
    img = Image.open(img_path).convert("RGB")
    img_w, img_h = img.size
    mode = _pick_motion_mode()
    ss = max(1, int(SUPERSAMPLE))
    ss_w, ss_h = TARGET_W * ss, TARGET_H * ss
    def make_frame(t):
        progress = min(1.0, t / duration) if duration > 0 else 0.0
        e = _ease_in_out(progress)
        sw, sh, cx, cy = _crop_for_mode(mode, e, img_w, img_h)
        frame = img.crop((cx, cy, cx + sw, cy + sh)).resize((ss_w, ss_h), Image.Resampling.LANCZOS)
        if ss > 1: frame = frame.resize((TARGET_W, TARGET_H), Image.Resampling.LANCZOS)
        frame_np = np.array(frame)
        if text_overlay: frame_np = draw_text_overlay(frame_np, text_overlay)
        return frame_np
    return ImageClip(make_frame(0)).set_duration(duration).set_make_frame(make_frame)

def cover_resize(img, target_w, target_h):
    src_w, src_h = img.size
    scale = max(target_w / src_w, target_h / src_h)
    new_w, new_h = int(round(src_w * scale)), int(round(src_h * scale))
    resized = img.resize((new_w, new_h), Image.Resampling.LANCZOS)
    left, top = (new_w - target_w) // 2, (new_h - target_h) // 2
    return resized.crop((left, top, left + target_w, top + target_h))

# Zpracování snímků a export videa
# Zde aktualizujeme image_files a nastavení rozměrů, které závisí na fotkách
image_files = sorted([os.path.join(INPUT_DIR, f) for f in os.listdir(INPUT_DIR) if f.lower().endswith(('.png', '.jpg', '.jpeg', '.webp'))], key=natural_sort_key)
print(f"📷 Počet nalezených snímků: {len(image_files)}")

if not image_files:
    raise ValueError("❌ Žádné fotografie nebyly nalezeny v INPUT_DIR. Nahrajte je v předchozím kroku!")

DETECTED_RATIO = get_auto_aspect_ratio()
print(f"📌 Zjištěný poměr stran: {DETECTED_RATIO}")

TARGET_W, TARGET_H = (1920, 1080) if DETECTED_RATIO == "16:9" else (1440, 1080)
WORK_W, WORK_H = int(round(TARGET_W * MOTION_OVERSCAN)), int(round(TARGET_H * MOTION_OVERSCAN))

for idx, img_path in enumerate(image_files):
    target_p = os.path.join(ENHANCED_DIR, os.path.basename(img_path).split('.')[0] + ".png")
    img = Image.open(img_path).convert("RGB")
    img = cover_resize(img, WORK_W, WORK_H)
    img.save(target_p, "PNG", quality=100)

final_image_paths = sorted([os.path.join(ENHANCED_DIR, f) for f in os.listdir(ENHANCED_DIR) if f.endswith('.png')], key=natural_sort_key)
final_clips = []

# Intro
intro_lines = [MAKLER_JMENO, RK_NAZEV]
final_clips.append(create_centered_info_card(intro_lines, duration=VIDEO_FADE_IN, is_intro=True))

# Fotografie s animací
for idx, img_path in enumerate(final_image_paths):
    d = random.uniform(MIN_IMAGE_DURATION, MAX_IMAGE_DURATION)
    final_clips.append(apply_smooth_smart_motion(img_path, duration=d, text_overlay=GLOBAL_TEXT))

# Outro
outro_lines = [MAKLER_JMENO, RK_NAZEV, "Kontakt:"]
if MAKLER_EMAIL: outro_lines.append(MAKLER_EMAIL)
if MAKLER_TELEFON: outro_lines.append(MAKLER_TELEFON)
final_clips.append(create_centered_info_card(outro_lines, duration=VIDEO_FADE_OUT, is_intro=False))

if final_clips:
    final_video = concatenate_videoclips(final_clips, method="compose", padding=-1.0)
    total_dur = final_video.duration

    if os.path.exists(MUSIC_FILE):
        audio = AudioFileClip(MUSIC_FILE)
        # Kompatibilita s MoviePy v2 a v1 pro hlasitost a loop
        try:
            audio = audio.volumex(VOLUME / 100.0)
        except AttributeError:
            audio = audio.multiply_volume(VOLUME / 100.0)

        if audio.duration < total_dur:
            try:
                audio = audio.fx(afx.audio_loop, duration=total_dur)
            except:
                # Fallback pro starší verze nebo specifické chyby
                from moviepy.audio.fx.all import audio_loop
                audio = audio_loop(audio, duration=total_dur)
        else:
            audio = audio.set_duration(total_dur)

        # Kompatibilita pro audio fade efekty (MoviePy v1 vs v2)
        try:
            audio = audio.audio_fadein(AUDIO_FADE_IN).audio_fadeout(AUDIO_FADE_OUT)
        except AttributeError:
            import moviepy.audio.fx.all as afx_all
            audio = afx_all.audio_fadein(audio, AUDIO_FADE_IN)
            audio = afx_all.audio_fadeout(audio, AUDIO_FADE_OUT)

        final_video = final_video.set_audio(audio)

    class SimplePercentageLogger(ProgressBarLogger):
        def __init__(self):
            super().__init__()
            self.last_pct = -1
        def callback(self, **changes):
            if 't' in self.bars and self.bars['t']['total'] > 0:
                pct = int((self.bars['t']['index'] / self.bars['t']['total']) * 100)
                if pct != self.last_pct:
                    sys.stdout.write(f"\r🚀 Rendering: {pct}%")
                    sys.stdout.flush()
                    self.last_pct = pct

    print(f"🎬 Délka: {total_dur:.1f}s. Zahajuji export...")
    final_video.write_videofile(OUTPUT_FILE, fps=TARGET_FPS, codec="libx264", audio=os.path.exists(MUSIC_FILE), threads=4, logger=SimplePercentageLogger())
    print("\n✅ Hotovo!")

    if IS_COLAB:
        files.download(OUTPUT_FILE)

# Volání notify.py po dokončení prvního videa (video 1)
if os.path.exists(OUTPUT_FILE):
    notify_video_ready(OUTPUT_FILE)

"""```markdown
# 🤖 Komentář Gemini
Tato buňka vygeneruje marketingový popisek k videu na základě obsahu vašich fotografií (vyjma úvodní a závěrečné stránky).
```
"""

# @title 📝 Generovat doprovodný komentář
import google.generativeai as genai
from PIL import Image

def generate_video_commentary():
    global gemini_output_text
    try:
        if IS_COLAB:
            api_key = userdata.get('GOOGLE_API_KEY')
        else:
            api_key = os.environ.get('GOOGLE_API_KEY')
            if not api_key:
                raise RuntimeError(
                    "Chybí GOOGLE_API_KEY (v GitHub Actions musí být nastaven jako "
                    "env proměnná ze secrets ve kroku 'Render video')."
                )
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel(GEMINI_MODEL)

        all_photos = sorted([os.path.join(INPUT_DIR, f) for f in os.listdir(INPUT_DIR)
                             if f.lower().endswith(('.png', '.jpg', '.jpeg', '.webp'))], key=natural_sort_key)

        if len(all_photos) <= 2:
            print("⚠️ Nedostatek fotografií.")
            return None

        analysis_photos = all_photos[1:-1]

        # Načtení aktuálních dat z konfigurace
        t_top = globals().get('TEXT_TOP', 'Nemovitost')
        t_bottom = globals().get('TEXT_BOTTOM', 'Lokalita')

        # Definice promptu s přímým vložením textových polí
        prompt_text = (
            f"Jsi profesionální realitní copywriter a spíkr. Tvým úkolem je vytvořit souvislý, poutavý a prodejní text pro hlasový doprovod realitního videa bez použití klišé. "
            f"Video začíná prvním snímkem. V úvodu pro definici typu nemovitosti a lokality využij výběr z těchto údajů: '{t_top}' a '{t_bottom}' bez uvádění výměrv m2, neuváděj zkratky např RD, kromě hovorových výrazů jako je + kk, ale plné výrazy. "
            "Následně se zcela vyhni popisu jednotlivých snímků vteřinu po vteřině. Místo toho pracuj v širších tematických blocích (vstup, hlavní obytný prostor, privátní část, zahrada). "
            "Text musí působit elegantně, plynule a přirozeně, tvoř delší navazující myšlenky. Zaměř se na atmosféru, dispozici a materiály. "
            "V žádném případě nelži, nevymýšlej si neověřitelné parametry a striktně se vyhni klišé typu 'oáza klidu', 'snové bydlení' nebo 'srdce domova'. "
            "Nezmiňuj žádná data, jména makléřů ani pozdravy a začni bez omáčky. Výsledkem musí být pouze čistý text pro mluvený přednes."
        )

        content_parts = [prompt_text]

        print(f"🧠 Analyzuji snímky pomocí {GEMINI_MODEL}... (Vstupní texty: {t_top} | {t_bottom})")
        for img_path in analysis_photos:
            content_parts.append(Image.open(img_path))

        response = model.generate_content(content_parts)
        gemini_output_text = response.text

        print("\n--- DOPROVODNÝ KOMENTÁŘ GEMINI ---\n")
        print(gemini_output_text)
        return gemini_output_text

    except Exception as e:
        print(f"❌ Chyba: {e}")
        return None

gemini_output_text = generate_video_commentary()

"""```markdown
# 🎙️ Profesionální Hlasový Doprovod (Synchronizovaný TTS)
Tato buňka převede text z Gemini na hlas v češtině. Komentář je časově přizpůsoben stávající délce videa a doprovázen funkcí ducking (ztlumení hudby při mluvení).
```
"""

# @title 🔊 Profesionální HLAS a DYNAMICKÉ TITULKY
# Pozn.: "!" příkazy jsou platné jen jako magic buňky v Colabu - v headless
# běhu (python video.py job.json) by ze scriptu udělaly SyntaxError a celý
# render by spadl ještě před dokončením videa 1. Proto se spouští jen v
# Colabu; v GitHub Actions musí ImageMagick + edge-tts/pydub zajistit
# workflow (apt balíček imagemagick) a requirements.txt (edge-tts, pydub).
if IS_COLAB:
    subprocess.run(["apt-get", "install", "-y", "imagemagick"], check=False)
    subprocess.run(
        ["sed", "-i",
         's/domain="path" rights="none" pattern="@\\*"/domain="path" rights="read|write" pattern="@*"/g',
         "/etc/ImageMagick-6/policy.xml"],
        check=False,
    )
    install("edge-tts")
    install("pydub")

import edge_tts
import re
import sys
import os
import textwrap
import google.generativeai as genai
from moviepy.editor import VideoFileClip, AudioFileClip, CompositeAudioClip, TextClip, CompositeVideoClip
from moviepy.config import change_settings
from proglog import ProgressBarLogger

change_settings({"IMAGEMAGICK_BINARY": "/usr/bin/convert"})

def clean_ai_text(text):
    text = re.sub(r'\\*\\*', '', text)
    text = re.sub(r'#.*', '', text)
    return text.replace('\\n', ' ').strip()

def split_text_to_max_lines(text, max_chars_per_line=45, max_lines=2):
    max_chunk_length = max_chars_per_line * max_lines
    words = text.split()
    chunks = []
    current_chunk = []
    current_length = 0

    for word in words:
        if current_length + len(word) + 1 > max_chunk_length:
            chunks.append(" ".join(current_chunk))
            current_chunk = [word]
            current_length = len(word)
        else:
            current_chunk.append(word)
            current_length += len(word) + 1

    if current_chunk:
        chunks.append(" ".join(current_chunk))
    return chunks

async def translate_sentences(sentences_list):
    print(f"🌐 Překládám a čistím titulky...")
    model = genai.GenerativeModel(GEMINI_MODEL)
    translated = []
    for s in sentences_list:
        prompt = f"Translate the following Czech real estate text into professional English subtitles. Output ONLY the translated text, no symbols, no formatting, no stars, no arrows. Czech text: {s}"
        resp = model.generate_content(prompt)
        clean_res = resp.text.strip().replace('*', '').replace('>', '').replace('-', '').strip()
        translated.append(clean_res)
    return translated

async def create_pro_voiceover_async(text_to_speak, video_in_path):
    if not text_to_speak: return
    clean_text = clean_ai_text(text_to_speak)

    try:
        video = VideoFileClip(video_in_path)
        start_delay = float(VOICE_START_DELAY)
        available_time = video.duration - start_delay - float(VOICE_END_PADDING)

        voice_tmp = "voice_antonin.mp3"

        async def check_dur(txt):
            c = edge_tts.Communicate(txt, "cs-CZ-AntoninNeural", rate=VOICE_SPEED)
            await c.save(voice_tmp)
            a = AudioFileClip(voice_tmp)
            d = a.duration
            a.close()
            return d

        sentences = re.split(r'(?<=[.!?]) +', clean_text)
        while len(sentences) > 1 and (await check_dur(" ".join(sentences))) > available_time:
            sentences.pop()

        print(f"✅ Text připraven ({len(sentences)} vět).")
        en_sentences = await translate_sentences(sentences)

        print(f"🎤 Generuji synchronizované audio a titulky s kompaktním pozadím...")

        audio_clips = []
        subtitle_clips = []
        current_time = start_delay
        sub_color = SUBTITLE_COLOR if 'SUBTITLE_COLOR' in globals() else 'white'

        for i, (cz_s, en_s) in enumerate(zip(sentences, en_sentences)):
            tmp_path = f"part_{i}.mp3"
            c = edge_tts.Communicate(cz_s, "cs-CZ-AntoninNeural", rate=VOICE_SPEED)
            await c.save(tmp_path)

            part_audio = AudioFileClip(tmp_path).set_start(current_time)
            total_dur = part_audio.duration
            audio_clips.append(part_audio)

            # Rozdělení na menší kousky pro titulky
            sub_chunks = split_text_to_max_lines(en_s, max_chars_per_line=40, max_lines=2)
            sub_time = current_time
            total_chars = sum(len(c) for c in sub_chunks) if sub_chunks else 1

            for chunk in sub_chunks:
                chunk_dur = total_dur * (len(chunk) / total_chars)

                # Změna: method='label' zajistí, že podklad bude jen pod textem, ne přes celou šířku
                sub = TextClip(chunk, fontsize=int(SUBTITLE_SIZE), color=sub_color,
                               font='DejaVu-Sans-Bold',
                               bg_color='rgba(64,64,64,0.7)', # Průhlednější šedá
                               method='label')

                # Pokud je titulek širší než 80% videa, zmenšíme ho (bezpečnostní pojistka)
                if sub.w > video.w * 0.8:
                    sub = sub.resize(width=int(video.w * 0.8))

                sub = sub.set_start(sub_time).set_duration(chunk_dur).set_position(('center', video.h * SUBTITLE_Y_POSITION))

                subtitle_clips.append(sub)
                sub_time += chunk_dur

            current_time += total_dur

        voice_group = CompositeAudioClip(audio_clips)

        if video.audio:
            v_start, v_end = start_delay, current_time
            music = video.audio.fl(lambda gf, t: gf(t) * (0.15 if v_start <= t <= v_end else 1.0))
            final_audio = CompositeAudioClip([music, voice_group.volumex(1.4)])
        else:
            final_audio = voice_group

        final_video = CompositeVideoClip([video] + subtitle_clips).set_audio(final_audio)
        out_name = "video_final.mp4"

        print(f"🎬 Exportuji finální video (Start: {start_delay}s)... Celkem {len(subtitle_clips)} segmentů titulků")
        final_video.write_videofile(out_name, fps=TARGET_FPS, codec="libx264", audio_codec="aac")

        if IS_COLAB: files.download(out_name)
        print(f"\\n✅ Hotovo! Video je uloženo jako {out_name}.")

    except Exception as e:
        print(f"\\n❌ Chyba: {e}")

# Pozn.: samostatné "await" na nejvyšší úrovni je platné jen uvnitř
# Jupyter/Colab kernelu (interpretuje ho speciálně) - jako obyčejný .py
# skript je to SyntaxError a "python video.py job.json" by spadl ještě
# před vygenerováním videa 2. asyncio.run() funguje spolehlivě v obou
# prostředích (Colab i headless GitHub Actions).
import asyncio
asyncio.run(create_pro_voiceover_async(globals().get('gemini_output_text'), OUTPUT_FILE))

# Volání notify.py po dokončení finálního videa (video 2)
if os.path.exists('video_final.mp4'):
    notify_video_ready('video_final.mp4')